# 数据源配置
spring:
  datasource:
    # 主库数据源
    master:
      jdbcUrl: jdbc:postgresql://43.140.198.24:5432/shop
      username: postgres
      password: 5ZwHkMb3yXZ7DAxIvqWmyI1K
    # 从库数据源
    slave:
      # 从数据源开关/默认关闭
      enabled: false
      jdbcUrl:
      username:
      password:
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: org.postgresql.Driver